name: Build

on:
  push:
    branches:
      - develop
    paths-ignore:
      - ".github/**"
      
jobs:
  create-draft-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get short SHA
        id: get_sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Create draft PR
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          commit-message: 'Promote latest build to test'
          branch: promotion/test-pr  # Change this to your desired branch name
          base: develop  # Change to your default branch
          title: 'Promote latest build to test - SHA: ${{ steps.get_sha.outputs.sha }}'
          body: |
            This PR promotes the latest build to the test environment.
            
            SHA: ${{ steps.get_sha.outputs.sha }}

      - name: Output PR URL
        run: |
          echo "Pull Request URL: ${{ steps.create_pr.outputs.html_url }}"
