name: Deploy to Test

on:
  repository_dispatch:
    # Trigger from repository dispatch workflow in promotion/test branch
    types: [trigger-test-deploy]

env:
  PROD_PROMO_BRANCH: promotion/prod
  PROD_PROMO_PR_BRANCH: promotion/prod-pr

jobs:
  deploy:
    name: Deploy to Test
    runs-on: ubuntu-20.04
    outputs:
      COMMIT_SHA: ${{ steps.read-hash.outputs.SHA }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: "promotion/test"
      - name: Retrieve previous commit hash
        id: read-hash
        run: echo "::set-output name=SHA::`jq -r '.commit' state.json`"