name: only run Manual

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
      working-directory: ./

jobs:
  SayHello:
    runs-on: ubuntu-20.04
    environment:
      name: test
    steps:
      - name: echoer
        run: echo "echo this"
